name: RavvenBase
main: com.gmail.ravvenlord.ravvenplug.RavvenBase
version: 0.1
commands:
  pos:
    description: Bla Bla Bla
    usage: "Usage: '/pos' to get current position, or '/pos x y z' to teleport to x,y,z"
  debug:
    description: Toggles your debugging status for this plugin.
    usage: /debug
  army:
    description: Span Mob attacking nearest entity.
    usage: /army
    